# Generated by Django 4.0.1 on 2024-04-12 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=200)),
                ('nascimento', models.DateField()),
                ('crm', models.IntegerField(max_length=10)),
                ('especialidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_medicos.especialidade')),
            ],
        ),
    ]
