# Generated by Django 4.0.1 on 2024-04-12 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicos',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='telefone',
        ),
    ]
