# Generated by Django 4.0.1 on 2024-04-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicos', '0002_remove_medicos_crm_remove_medicos_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicos',
            old_name='especialidade_id',
            new_name='especialidade',
        ),
        migrations.AddField(
            model_name='medicos',
            name='crm',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='medicos',
            name='telefone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
