# Generated by Django 5.0.4 on 2024-05-05 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicos', '0003_rename_especialidade_id_medicos_especialidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('nascimento', models.DateField()),
                ('crm', models.CharField(default='', max_length=10)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_medicos.especialidade')),
            ],
        ),
        migrations.DeleteModel(
            name='Medicos',
        ),
    ]
