# Generated by Django 5.0.4 on 2024-05-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicos', '0004_medico_delete_medicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
    ]
